config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :events
  resources :alarms

  resources :alarms do
    post :match, on: :member
  end

  get "welcome/index"
  root "welcome#index"

  get "/flows/master", to: "flow#new_master"
  get "/flows", to: "flow#new_matcher"
end

app/models/alarm.rb
# frozen_string_literal: true

class Alarm < ApplicationRecord
  has_many :events
  has_many :flows

  accepts_nested_attributes_for :events, allow_destroy: true

  def add_flows(params)
    capabilities = params.to_h[:events_attributes]
    matchers = []

    capabilities.each do |filter|
      matchers << {
        capability: filter[:capability],
        comparator: map_comparator(filter[:comparator]),
        value:      filter[:value]
      }
    end
    matchers.each { |match| add_flow match }
  end

  def map_comparator(comparator)
    return "lt" if comparator == "<"
    return "gt" if comparator == ">"
    return "eq" if comparator == "="
  end

  def add_flow(matcher)
    flow = Flow.build_matcher(self, matcher)
    flow.save
    Flow.find_by_name(matcher[:capability]).flow_linkage flow
    flows << flow
  end

  def actived?
    flows.map(&:status).all?
  end
end

app/controllers/alarms_controller.rb
# frozen_string_literal: true

require_relative "../../lib/notifications/notification_factory.rb"

class AlarmsController < ApplicationController
  before_action :set_alarm, only: %i[show edit update destroy match]
  protect_from_forgery unless: -> { request.format.json? }

  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.all
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show; end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
    2.times { @alarm.events.build }
  end

  # GET /alarms/1/edit
  def edit; end

  # POST /alarms
  # POST /alarms.json
  def create
    @alarm = Alarm.new(alarm_params)

    respond_to do |format|
      if @alarm.save
        @alarm.add_flows(alarm_params)
        format.html { redirect_to @alarm, notice: "Alarm was successfully created." }
        format.json { render :show, status: :created, location: @alarm }
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    respond_to do |format|
      if @alarm.update(alarm_params)
        format.html { redirect_to @alarm, notice: "Alarm was successfully updated." }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    @alarm.destroy
    respond_to do |format|
      format.html { redirect_to alarms_url, notice: "Alarm was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def match
    result = params[:result]
    if result
      if @alarm.actived?
        comp = NotificationFactory.new
        notification = comp.get_notification(@alarm)
        notification.send
        @alarm.actived = true
        @alarm.save
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_alarm
    @alarm = Alarm.find(params[:id])
    return unless @alarm

    # flow = Flow.find_by(name: params[:id]).first
    # flow.update_attributes(status: true)
    # @alarm = flow.alarm
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def alarm_params
    params.require(:alarm).permit(
      :user_id, :name, :actived, :latitude, :longitude, :email, :sms, :webhook, :flow_id,
      events_attributes: %i[capability comparator value _destroy]
    )
  end
end

app/helpers/alarms_helper.rb
# frozen_string_literal: true

module AlarmsHelper
end

app/views/alarms/_form.html.erb
<%= form_with(model: alarm, local: true) do |form| %>
  <% if alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :alarm_user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :alarm_name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :alarm_latitude, class: :text_field, step: :any %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :alarm_longitude, class: :text_field, step: :any %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.check_box :email, id: :alarm_email %>
  </div>

  <div class="field">
    <%= form.label :sms %>
    <%= form.check_box :sms, id: :alarm_sms %>
  </div>

  <div class="field">
    <%= form.label :webhook %>
    <%= form.text_field :webhook, id: :alarm_webhook %>
  </div>

  <div class="field">
    <%= form.label :actived %>
    <%= form.check_box :actived, id: :alarm_actived %>
  </div>

  Events:
  <ul>
    <%= form.fields_for :events do |events_form| %>
      <li>
        <%= events_form.label :capability %>
        <%= events_form.text_field :capability %>
        
        <%= events_form.label :comparator %>
        <%= events_form.text_field :comparator %>
        
        <%= events_form.label :value %>
        <%= events_form.text_field :value %>

        Destroy?
        <%= events_form.check_box :_destroy%>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alarms/edit.html.erb
<h1>Editing Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Back', alarms_path %>

app/views/alarms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alarms</h1>

<table>
  <thead>
    <tr>
      <th>User ID</th>
      <th>Name</th>
      <th>Actived</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Email</th>
      <th>SMS</th>
      <th>Webhook</th>
      <th>Flow ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alarms.each do |alarm| %>
      <tr>
        <td><%= alarm.user_id %></td>
        <td><%= alarm.name %></td>
        <td><%= alarm.actived %></td>
        <td><%= alarm.latitude %></td>
        <td><%= alarm.longitude %></td>
        <td><%= alarm.email %></td>
        <td><%= alarm.sms %></td>
        <td><%= alarm.webhook %></td>
        <td><%= alarm.flow_id %></td>
        <td><%= link_to 'Show', alarm %></td>
        <td><%= link_to 'Edit', edit_alarm_path(alarm) %></td>
        <td><%= link_to 'Destroy', alarm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alarm', new_alarm_path %>

app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Back', alarms_path %>

app/views/alarms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User ID:</strong>
  <%= @alarm.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @alarm.name %>
</p>

<p>
  <strong>Actived:</strong>
  <%= @alarm.actived %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @alarm.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @alarm.longitude %>
</p>

<p>
  <strong>Email:</strong>
  <%= @alarm.email %>
</p>

<p>
  <strong>SMS:</strong>
  <%= @alarm.sms %>
</p>

<p>
  <strong>Webhook:</strong>
  <%= @alarm.webhook %>
</p>

<p>
  <strong>Flow ID:</strong>
  <%= @alarm.flow_id %>
</p>

<%= link_to 'Edit', edit_alarm_path(@alarm) %> |
<%= link_to 'Back', alarms_path %>