config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :events
  resources :alarms

  resources :alarms do
    post :match, on: :member
  end

  get "welcome/index"
  root "welcome#index"

  get "/flows/master", to: "flow#new_master"
  get "/flows", to: "flow#new_matcher"
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :alarm
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  protect_from_forgery unless: -> { request.format.json? }

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:capability, :comparator, :value, :query_id)
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :capability %>
    <%= form.text_field :capability, id: :event_capability %>
  </div>

  <div class="field">
    <%= form.label :comparator %>
    <%= form.text_field :comparator, id: :event_comparator %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :event_value %>
  </div>

  <div class="field">
    <%= form.label :query_id %>
    <%= form.text_field :query_id, id: :event_query_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Capability</th>
      <th>Comparator</th>
      <th>Value</th>
      <th>Alarm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.capability %></td>
        <td><%= event.comparator %></td>
        <td><%= event.value %></td>
        <td><%= event.alarm_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Capability:</strong>
  <%= @event.capability %>
</p>

<p>
  <strong>Comparator:</strong>
  <%= @event.comparator %>
</p>

<p>
  <strong>Value:</strong>
  <%= @event.value %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>